### ISSUE TITLE
Problem when opening multiple windows at the same time

### ISSUE THREAD

**Issue by sanggonlee** [danielstjules/blankshield#11]
Hello, I am getting a null reference error when doing something like this:
`
urls.forEach(url => {
  blankshield.open(url, '_blank');
});
`
Looks like this is caused by the `child.opener = null` in `iframeOpen` function, preventing to execute this line for the second time and onwards.

**Comment by danielstjules** [comment]
This is because most browsers won't let you open windows in a loop, so the child window ends up being null for every subsequent invocation of `window.call`. For example, this will fail to open more than 1 window:
``` javascript
['https://github.com', 'https://github.com'].forEach(url => { window.open(url, '_blank') });
```
Will update the code to prevent throwing an error :)
