### ISSUE TITLE
event.preventDefault not working in Firefox

### ISSUE THREAD

**Issue by jonny-harte** [danielstjules/blankshield#17]
Hi,

I have event.preventDefault on links that open a new tab so the user has to fill in a form before they can see the content. It works fine in Chrome but in Firefox and Edge it still opens the new tab when they click the download links. 

It works fine on my local version that has iTheme security disabled, but when I move it to my server an extra event handler is added which seems to be causing the problem.

https://seerene.harte.online/download-center - click the download links.

```
$('body').on('click', '.file-download', function (event) {
      if ($('.download-overlay').length !== 1) {
        return;
      }
      // Stop default action and bubbling
      event.preventDefault();
      event.stopPropagation();

      $('.download-overlay').find('.download-title').text($(this).attr('title'));
      $('.download-overlay').attr('data-file', $(this).attr('href'));

      $('.download-overlay').fadeIn(200);
      $('body').addClass('overlay-open');
    });
```

**Comment by Encorehwang** [comment]
I met same problem, how do you fix it?
