### ISSUE TITLE
Integration best practice

### ISSUE THREAD

**Issue by pastk** [danielstjules/blankshield#5]
What is the best place to invoke e.g. `blankshield($('a[target=_blank]'));` ?
To have all html parsed / DOM created by then I guess it should be done in document.onready.
But I wonder if its possible a user would click the unsafe link before its fixed (before the whole document is loaded and js run)?

Also at the moment the library doesn't support custom "target" attributes, e.g.`target="MyNewWindow"` - it'll open a new tab that will be vulnerable to the attack - I'm going to work on a patch for this issue.

**Comment by danielstjules** [comment]
I've just been using document ready. On a page (non-SPA) with 115 requests and 7MB of assets, DOMContentLoaded fired at 1.32s. However, the user may not be looking at anything for part of that 1.32s. So in the head of the page, I added: `var startTime = Date.now()`, and in the footer,

``` javascript
$(document).ready(function() {
  console.log('ready', Date.now() - startTime);
});
document.addEventListener('DOMContentLoaded', function() {
  console.log('DOMContentLoaded', Date.now() - startTime);
});

// ready 747
// DOMContentLoaded 771
```

So under a second. I think it's pretty safe to say that a user won't be able to recognize and consciously take action on a link as it's being rendered in that sort of time. Though I guess they could involuntarily click. For DOMContentLoaded to take a while, you'd have to be rendering MB of just HTML elements, or have a lot of blocking JS.

I might add a function that uses DOMNodeInserted and MutationObserver to handle anchors that are later added to the DOM. But unfortunately, neither would handle anchors that exist in the original markup.
